#
# This workflow will run all python integrations tests.
#

name: python-integration-tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  integration-tests:
    strategy:
        matrix:
          os: [ubuntu-latest]
          configuration: [Debug]

    runs-on: ${{ matrix.os }}
    needs: paths-filter
    if: needs.paths-filter.outputs.output1 == 'true'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    - name: Find Integration Tests
      shell: bash
      run: echo "TESTS=$(find ./python/tests/integration -type f -name "*_test.py" | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Run Integration Tests
      shell: bash
      env: # Set Azure credentials secret as an input
        AzureOpenAI__Label: azure-text-davinci-003
        AzureOpenAIEmbedding__Label: azure-text-embedding-ada-002
        AzureOpenAI__DeploymentName: ${{ vars.AZUREOPENAI__DEPLOYMENTNAME }}
        AzureOpenAIChat__DeploymentName: ${{ vars.AZUREOPENAI__CHAT__DEPLOYMENTNAME }}
        AzureOpenAIEmbeddings__DeploymentName: ${{ vars.AZUREOPENAIEMBEDDING__DEPLOYMENTNAME }}
        AzureOpenAI__Endpoint: ${{ secrets.AZUREOPENAI__ENDPOINT }}
        AzureOpenAIEmbeddings__Endpoint: ${{ secrets.AZUREOPENAI__ENDPOINT }}
        AzureOpenAI__ApiKey: ${{ secrets.AZUREOPENAI__APIKEY }}
        AzureOpenAIEmbeddings__ApiKey: ${{ secrets.AZUREOPENAI__APIKEY }}
        Bing__ApiKey: ${{ secrets.BING__APIKEY }}
        OpenAI__ApiKey: ${{ secrets.OPENAI__APIKEY }}
      run: |
        cd python
        for test in ${{ env.TESTS }}; do
          poetry run python $test
        done
